### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by pixelplanetdev**
Merged with @soyware 
Set up eslint and fixed all errors and warnings.
`npm run lint` for checking errors in code `npm run lint -- --fix` for automatically fixing whats possible to be fixed.

### CODE REVIEW

**Comment by soyware** [comment]
I don't understand why do you care about data past the end of the file so much

**Comment by pixelplanetdev** [comment]
@soyware true, better to focus on input.

I'm just being conservative with the data-past-EOF thing here. I wanted to look more into that at another time and maybe check if there's already some data past the end... so i just merged it together and kept old behavior for png for now.

**Comment by pixelplanetdev** [comment]
So, now the PNG hash gets changed by checking if there is a tIME chunk within the file... and if there is, changing its modification time.. and if there is none, adding one.

Fast, sticking to the specifications, legit file, not detectable and no pixel changes in any way
http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html

Not going to bother with the other formats.

**Comment by pixelplanetdev** [comment]
that crc just has to calculate for 11 bytes

**Comment by soyware** [comment]
You should time it against random pixel honestly

**Comment by pixelplanetdev** [comment]
```js
  const ss = Date.now();
  const crc = Number(crc32(tIME));
  console.log(`time pass: ${Date.now() - ss}ms`);
```
is always 0ms

While the File constructor is 3 to 4ms.

**Comment by soyware** [comment]
Yeah, random pixel is slow as shit lol, tested myself:

**1000 iterations, 48 KB PNG:**
CRC32: 100ms
Random data: 0ms
Random pixel: 5500ms

You can probably hide a message same way using tEXt chunk, if you want it to be visible to whoever checks text image properties

**Comment by pixelplanetdev** [comment]
Sure.
If you care a lot about performance, spotKym() is currently running over the whole document at each mutation, causing even more mutations in the process. That would be the only big TODO for now.

Can't use the TXT chunks because 4chan strips metadata and i am sure that those get lost.
I think PNG is done, can't do it much better. The CRC table is just generated once. I would not hardcode it, but i don't mind if you want to do that.

Looking into other file formats to find similar things that can be changed would be nice now.

**Comment by soyware** [comment]
CRC table is being generated on each page refresh, check yourself. There's literally nothing wrong with hardcoding CRC table https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/tier1/checksum_crc.cpp#L20 . Also PNG comments don't get stripped I just tested. I still use random data in my fork so I'm not gonna bother finding what to modify, might take a look at kym spotter though

**Comment by pixelplanetdev** [comment]
Fine, hardcoded the table now, cause you asked the second time now.

But i'm telling you that you are in a micro-optimization territory here where you will end up asking yourself at which length parsing the values from the unicode formatted js file starts being slower than parsing a function and calculating the values with a comparison and one or two bit operations.
That is a browser-dependent rabbit hole of autism.

**Pull request merged**
