### PR TITLE
Fixes and refactor

### PR DESCRIPTION
**Pull request by soyware**
Do the needful sir

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
image
>tabs

**Comment by HamletDuFromage** [comment]
On a more serious note, that is a little annoying that you did that
Thank you for the improvements though, I'll go through them somewhat soon and merge it then

**Comment by HamletDuFromage** [comment]
Also I'm aware the current id is dumb (was just a placeholder that somehow stuck), but wouldn't changing it break updates from installed addons?

**Comment by soyware** [comment]
Checking for updates didn't work for me before I changed the addon ID and I didn't really read what happens when you change it just remember that you'll have to upload it as a new addon to sign it or something.

**Comment by pixelplanetdev** [comment]
sorry, didn't check out this one before making my captcha-slider-solving pull-request, otherwise i would have just merged it together to not conflict.

Just some tiny thing, i think adding or slicing a few bytes off the file for hash randomizing could backfire, because another simple userscript could be able to check for trash at the end of a file and mark it, or mods could use it to ban.
I changed that random pixel for hash so that it stays closer to the original in my fork, it might be an option too.
It would also be nice to decide on some indentation style. Sometimes i got tabs, then 4 spaces, then 2.

The userscript keeps getting better, love it.

**Comment by HamletDuFromage** [comment]
I think I'm gonna cherry pick commits that fix bugs and manually add the useful lines from the commits that have heavy refactor. Then it should be pretty painless to merge your work @pixelplanetdev 

Is there some commonly accepted formatting style for JavaScript? If so we do it properly in one commit after all is merged

**Comment by pixelplanetdev** [comment]
eslint with airbnb config is quite common and can --fix basic issues like indentation, trailing whitespaces, etc. automatically.

You can try it with 
```
npm install eslint --save-dev
npm install eslint-config-airbnb-base --save-dev
```
and a basic `.eslintrc.json`
```
{
  "extends": "airbnb-base",
  "env": {
    "browser": true
  },
  "globals": {
    "browser": "readonly"
  }
}

```
and a script in package.json
```
    "scripts": {
        "dev": "webpack --mode=development --watch",
        "build": "webpack --mode=production",
        "lint": "eslint --ext .js src"
    },
```

Then `npm run lint` would show you the errors and `npm run lint -- --fix` would automatically fix what it can.
Airbnb is a common ruleset and very autistic with some things, but rules can be individually turned off.
It will do a 2-space-indentation.

**Comment by pixelplanetdev** [comment]
Turning the most autistic rules off, like this .eslintrc.json, leaves us with 64 problems having to be manually fixed. Most of it unused variables and lines being too long.

```
{
  "extends": "airbnb-base",
  "env": {
    "browser": true
  },
  "globals": {
    "browser": "readonly"
  },
  "rules": {
    "no-plusplus": "off",
    "no-console": "off",
    "default-case": "off",
    "no-continue": "off",
    "no-mixed-operators": "off"
  }
}
```

Your decision if you want to go the whole way and do proper linting in that little extension. I'm ready to fix all the issues in the code that i caused if you decide to go for it.

**Comment by HamletDuFromage** [comment]
actually it looks like I had already merged the important stuff. I'll be closing the PR now. @soyware let me know if you think I missed something

**Comment by soyware** [comment]
Commits after [e09ebdd](https://github.com/HamletDuFromage/4chan-mass-reply/pull/12/commits/e09ebdd8266a8de0d7ad09976cf78fec86bda333) make the popup look consistant across the browsers and some better variable naming as well as fixing printing that we compressed if we didn't.

@pixelplanetdev the reason for that change other than it's faster is that you can spam with all types of files (WebM, GIF, probably SWF and PDF) not just JPG and PNG, banning or filtering based on that would probably have many false positives.

**Comment by pixelplanetdev** [comment]
@soyware i understand, sounds great then. Do you have any idea how much we can add at the end of files till it corrupts a png? Like how many times i could save -> post -> save result -> post till its broken.

If we are adding stuff at the end of those files, we could do something fun with it. Like hiding a message that just people who have the extension can see.

**Comment by pixelplanetdev** [comment]
The image-reuse always used the original, i was thinking about people saving it and posting it themselves.

Yes, i said they stand out of the crowd. But if it stands out anyway, might as well use it.

I imagine that the formats that do not care about the padding go by image dimension and don't read further once it got all pixels, which should make it easy to detect when there's something added.

**Pull request closed without merging**
