### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by soyware**
- fixed hash changer for webms and big gifs
- changed "lint-fix" npm script to "lint"

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
neato :)

**Comment by soyware** [comment]
forgot to mention hash changer fucks up the end of webms a bit, there may be better alternative

**Comment by HamletDuFromage** [comment]
eh, I assume it's fine

**Comment by soyware** [comment]
and i was thinking maybe copypastas should be removed? every respectable shitposter has his own list of copypastas

**Comment by HamletDuFromage** [comment]
The reason I added that to begin with is because I didn't have my own. Then again I never use them and haven't added new ones in forever

**Pull request merged**
