### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by soyware**
- Changed memeflag emoji
- Fixed report page captcha autoslide
- Removed context menu to make extension compatible with mobile
- Added "lint-fix" npm script to fix linting automatically

### CODE REVIEW

**Comment by HamletDuFromage** [comment]
Looks good, thank you :)

**Comment by HamletDuFromage** [comment]
> Removed context menu to make extension compatible with mobile
btw was that necessary? It worked fine on [SmartCookieWeb Preview](https://github.com/CookieJarApps/SmartCookieWeb-Preview/releases/latest) and some simpleton in the issues seems to miss it. Which mobile browser are you using the extension on?

**Comment by soyware** [comment]
If I remember correctly when I was debugging smartcookieweb preview it was erroring out on context menu stuff, which was causing copypastas to not load. You say it was working fine, how do you even open context menu on mobile?

**Comment by HamletDuFromage** [comment]
Actually you're right, copypastas aren't loading on mobile. And no, you can't open the context menu on mobile afaik

Maybe deleting cookies can be done through a button on the extension window? Because deleting 4chan and 4channel cookies at the same time was convenient I guess

**Comment by soyware** [comment]
done

**Pull request merged**
